### PR TITLE
Create pythonproject20

### PR DESCRIPTION
**Pull request by AYUSHSURYAVANSHI**

### CODE REVIEW

**Review by KhushbooGupta2111 — CHANGES_REQUESTED** [review]
Please push the file inside the named folder under python project. You can refer to python projects folder.

**Review by hiferli — CHANGES_REQUESTED** [review]
Please add this in the 'Python Projects' folder 

Thanks

**Review by KhushbooGupta2111 — APPROVED** [review]
Made the required changes

**Comment by KhushbooGupta2111** [comment]
@hiferli approve

**Review by hiferli — APPROVED** [review]

**Pull request merged**
