### PR TITLE
added Digit Recognition code file

### PR DESCRIPTION
**Pull request by kanchi12P**
Handwritten Digits Classification

### CODE REVIEW

**Comment by KhushbooGupta2111** [comment]
@kanchi12P, please add a readme file.

**Review by KhushbooGupta2111 — CHANGES_REQUESTED** [review]
Please add a readme file explaining about the project and the changes you would wish from other contributors.

**Comment by kanchi12P** [comment]
@KhushbooGupta2111 I have added the readme file.
Please review.

**Review by KhushbooGupta2111 — APPROVED** [review]
As of now it's fine, please try adding more details in readme file.

**Review by hiferli — APPROVED** [review]

**Review by hiferli — APPROVED** [review]

**Comment by kanchi12P** [comment]
please attach the hacktoberfest tag @hiferli

**Pull request merged**
