### PR TITLE
Multiple stack

### PR DESCRIPTION
**Pull request by MAYURIKOTHARI299**

### CODE REVIEW

**Review by KhushbooGupta2111 — CHANGES_REQUESTED** [review]
Please push this code under cpp directory

**Comment by MAYURIKOTHARI299** [comment]
i changed the file location to cpp

**Comment by MAYURIKOTHARI299** [comment]
@KhushbooGupta2111 I made the changes

**Review by KhushbooGupta2111 — APPROVED** [review]

**Review by hiferli — APPROVED** [review]

**Review by hiferli — APPROVED** [review]

**Comment by hiferli** [comment]
Thank you for making the changes.
We appreciate your patience :)

Thanks

**Pull request merged**
