### PR TITLE
Multiple stacks

### PR DESCRIPTION
**Pull request by MAYURIKOTHARI299**

### CODE REVIEW

**Review by KhushbooGupta2111 — APPROVED** [review]

**Review by hiferli — COMMENTED** [review]
I mentioned these changes in the PR made for Analog Clock.
Please refer to those changes

**Review by hiferli — APPROVED** [review]

**Comment by MAYURIKOTHARI299** [comment]
> I mentioned these changes in the PR made for Analog Clock.
> Please refer to those changes

Hey! 
Do I need to create a folder named stacks for this too and then add my files?

**Comment by hiferli** [comment]
No you don't have to create a subfolder for the Data Structure.
Just add the code in the corresponding coding language subfolder

**Comment by hiferli** [comment]
Moreover, you have a different PR raised for the Analog Clock project.
Can you remove the Analog project files from this PR?
They are creating conflicts over here.

Thanks

**Comment by MAYURIKOTHARI299** [comment]
hey i dont get it what is the issue with this pr...i got the analog clock one but this one is not repeated. This got approved but is not merged yet.

**Comment by KhushbooGupta2111** [comment]
@MAYURIKOTHARI299,actually the issue is that you had raised more than 1 PR without being the previous one resolved.

**Comment by MAYURIKOTHARI299** [comment]
@KhushbooGupta2111 what should i do now how do i remove files

**Comment by KhushbooGupta2111** [comment]
@MAYURIKOTHARI299 make new PR, we will accept.

**Pull request closed without merging**
