### PR TITLE
Basic-portfolio

### PR DESCRIPTION
**Pull request by tinniaru3005**
A basic portfolio website to get started with.

### CODE REVIEW

**Comment by KhushbooGupta2111** [comment]
Hey @tinniaru3005! Please refrain from adding your personal details in the project. Kindly replace it with dummy text and images.

**Comment by tinniaru3005** [comment]
> Hey @tinniaru3005! Please refrain from adding your personal details in the project. Kindly replace it with dummy text and images.

Sure. I am making the changes and will let you know

**Comment by hiferli** [comment]
Hey Arunima.
Keeping in mind to keep your information confidential can you please change your social media credentials too?
We would like that your template is available as a portfolio

**Review by hiferli — APPROVED** [review]

**Comment by hiferli** [comment]
Awesome.
Thank You for making these changes :)

**Review by KhushbooGupta2111 — COMMENTED** [review]
Perfect now

**Comment by tinniaru3005** [comment]
> Perfect now

Thanks :)

**Pull request merged**
